# Generated by Django 5.0 on 2024-01-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
