# Generated by Django 5.0 on 2024-01-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaveenOrganicsApp', '0002_allfruits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mango',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('categoryName', models.CharField(max_length=50)),
                ('imgUrl', models.CharField(max_length=355)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'mango',
            },
        ),
    ]
