# Generated by Django 5.0 on 2024-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaveenOrganicsApp', '0005_cartitem_userprofile_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruitname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.IntegerField()),
                ('imgUrl', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
    ]
